name: marvel_hemisferio
description: Marvel

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_utilities:
    git:
      url: https://github.com/FabianVarela/json_utilities
  cupertino_icons: ^1.0.2
  injectable: ^1.5.4
  flutter_riverpod: ^2.1.1
  hooks_riverpod: ^2.1.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  go_router: ^5.1.5
  logger: ^1.1.0
  flutter_hooks: ^0.18.5+1
  formz: ^0.4.1
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.2
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  injectable_generator: ^1.5.5
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - locale/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 300
          style: italic